#!/bin/bash

declare -A dict

dict["abgeben"]="hand over"
dict["abheben"]="withdraw"
dict["abholen"]="pick up"
dict["ablaufen"]="expire"
dict["ablegen"]="take off"
dict["ablehnen"]="refuse"
dict["absetzen"]="drop"
dict["anrechnen"]="credit"
dict["abreissen"]="destroy"
dict["absagen"]="cancel"
dict["abschaffen"]="remove"
dict["abspeichern"]="save"
dict["absprechen"]="discuss"
dict["abspullen"]="rinse"
dict["abstellen"]="turn off"
dict["abschliessen"]="complete"
dict["abtrocken"]="dry"
dict["abwägen"]="weight up"
dict["abwiegen"]="measure"
dict["abwishen"]="wipe"
dict["abziehen"]="pull"
dict["achten"]="respect"
dict["anbitten"]="offer"
dict["anfassen"]="touch"
dict["anfertigen"]="make"
dict["angeben"]="specify"
dict["anhalten"]="stop"
dict["ankreuzen"]="check"
dict["annehmen"]="accept"
dict["anpassen"]="adjust"
dict["anschaffen"]="purchase"
dict["anspringen"]="start"
dict["anstellen"]="hire"
dict["antreten"]="start"
dict["anwenden"]="apply"
dict["aufnehmen"]="record"
dict["aufpassen"]="watch out"
dict["aufschreiben"]="write down"
dict["aufsetzen"]="set up"
dict["aufstocken"]="increase"
dict["auftragen"]="put on"
dict["ausgehen"]="run out"
dict["ausleihen"]="lend"
dict["auslesen"]="select"
dict["aussern"]="show"
dict["ausgeben"]="spend"
dict["ausmachen"]="turn off"
dict["ausrutschen"]="slip"
dict["auswandern"]="escape"
dict["basteln"]="craft"
dict["beachten"]="consider"
dict["beantragen"]="apply"
dict["bearbeiten"]="edit"
dict["bedienen"]="serve"
dict["befehlen"]="command"
dict["befristen"]="limit"
dict["begeistern"]="inspire"
dict["begleiten"]="escort"
dict["behalten"]="keep"
dict["behaupten"]="claim"
dict["beheben"]="repair"
dict["beherrschen"]="control"
dict["beladen"]="load"
dict["belegen"]="verify"
dict["belohnen"]="revard"
dict["bemuhen"]="bother"
dict["beraten"]="advise"
dict["bergen"]="save"
dict["bereinigen"]="clean up"
dict["berichten"]="report"
dict["beschliessen"]="decide"
dict["beschweren"]="complain"
dict["besichtigen"]="view"
dict["besprechen"]="discuss"
dict["bestatigen"]="confirm"
dict["bestehen"]="consist"
dict["bestimmen"]="specify"
dict["bestrafen"]="punish"
dict["betreuen"]="care"
dict["beurteilen"]="judge"
dict["bewegen"]="move"
dict["bewerben"]="apply"
dict["bezeichnen"]="indicate"
dict["beziehen"]="cover"
dict["biegen"]="bend"
dict["borgen"]="borrow"
dict["braten"]="roast"
dict["bugeln"]="iron"
dict["dazwischenkommen"]="intervene"
dict["drehen"]="turn"
dict["durchdringen"]="penetrate"
dict["durchfuhren"]="carry out"
dict["durchstreichen"]="cross out"
dict["eingeben"]="insert"
dict["einfugen"]="insert"
dict["einkennen"]="recognize"
dict["einlegen"]="insert"
dict["einsaugen"]="absorb"
dict["einschreiben"]="enroll"
dict["einseifen"]="soap"
dict["einstellen"]="hire"
dict["eintragen"]="register"
dict["einwirken"]="act"
dict["einziehen"]="move"
dict["empfangen"]="receive"
dict["entdecken"]="discover"
dict["entfernen"]="remove"
dict["entnehmen"]="remove"
dict["entscheiden"]="decide"
dict["erfahren"]="find out"
dict["erganzen"]="expend"
dict["erholen"]="recover"
dist["erkunden"]="explore"
dict["erlauben"]="allow"
dict["erleben"]="experience"
dict["erledigen"]="complete"
dict["ernennen"]="call"
dict["erschweren"]="complicate"
dict["erstatten"]="refund"
dict["erstellen"]="make"
dict["erziehen"]="educate"
dict["fangen"]="catch"
dict["fegen"]="brush"
dict["fehlen"]="lack"
dict["feststellen"]="notify"
dict["fliehen"]="flee"
dict["freistellen"]="release"
dict["frieren"]="freeze"
dict["futtern"]="feed"
dict["gedeihen"]="prosper"
dict["gehoren"]="belong"
dict["gelingen"]="succeed"
dict["gelten"]="count"
dict["genehmigen"]="approve"
dict["geniessen"]="enjoy"
dict["dennoch"]="nontheless"
dict["glanzen"]="shine"
dict["gleiten"]="slide"
dict["graben"]="dig"
dict["greifen"]="grasp"
dict["heben"]="lift"
dict["heiser"]="hoarse"
dict["herausbringen"]="release"
dict["herstellen"]="manufacture"
dict["herunterladen"]="download"
dict["hinnehmen"]="accept"
dict["hinterlassen"]="leave behind"
dict["hochfahren"]="boot up"
dict["hochladen"]="upload"
dict["klappen"]="succeed"
dict["knupfen"]="tie"
dict["krakelen"]="cry"
dict["krankmelden"]="report sick"
dict["krankschreiben"]="sick leave"
dict["kummern"]="care"
dict["kundigen"]="terminate"
dict["lacheln"]="smile"
dict["laden"]="load"
dict["lagern"]="store"
dict["leiden"]="suffer"
dict["leihen"]="lend"
dict["leisten"]="afford"
dict["leiten"]="lead"
dict["loben"]="praise"
dist["lohnen"]="worth"
dict["loschen"]="delete"
dict["losen"]="solve"
dict["losfahren"]="launch"
dict["meinen"]="mean"
dict["melden"]="enroll"
dict["messen"]="measure"
dict["nachschlagen"]="search"
dict["nahen"]="sew"
dict["nennen"]="call"
dict["passen"]="fit"
dict["pflegen"]="cultivate"
dict["plaundern"]="chat"
dict["reklamieren"]="complain"
dict["rasen"]="rage"
dict["reiben"]="rub"
dict["reissen"]="tear"
dict["rupfen"]="pluck"
dict["sammeln"]="collect"
dict["saugen"]="vacuum"
dict["schaffen"]="manage"
dict["scheiden"]="separate"
dict["schieben"]="push"
dict["schiessen"]="shoot"
dict["schlagen"]="hit"
dict["schneiden"]="cut"
dict["schutzen"]="protect"
dict["schweigen"]="calm"
dict["siegen"]="win"
dict["sparen"]="save"
dict["spitzen"]="point"
dict["springen"]="jump"
dict["spruhnen"]="spray"
dict["stattfinden"]="take place"
dict["stechen"]="pierce"
dict["steigen"]="rise"
dict["stolpern"]="stumble"
dict["stossen"]="ram"
dict["streichen"]="paint"
dict["tauschen"]="change"
dict["teilnehmen"]="participate"
dict["toben"]="roar"
dict["trennen"]="separate"
dict["uben"]="practice"
dict["uberlegen"]="consider"
dict["ubernehmen"]="take over"
dict["ubertragen"]="relay"
dict["umgehen"]="bypass"
dict["umsehen"]="browse"
dict["umsetzen"]="implement"
dict["unterstutzen"]="support"
dict["unterzeichnen"]="sign"
dict["verabreden"]="arrange"
dict["verabschieden"]="goodbye"
dict["verberden"]="spoil"
dict["verbergen"]="hide"
dict["verbeugen"]="bow"
dict["verbinden"]="connect"
dict["verbringen"]="spend"
dict["vereinbaren"]="agree"
dict["verfassen"]="write"
dict["vergleichen"]="compare"
dict["verlangen"]="demand"
dict["verheimlichen"]="hide"
dict["verhindern"]="prevent"
dict["verlangern"]="extend"
dict["verlegen"]="lay"
dict["verletzen"]="injure"
dict["verlieren"]="lose"
dict["vermeiden"]="avoid"
dict["vermessen"]="measure"
dict["vermitteln"]="give"
dict["verschieben"]="shift"
dict["verschoben"]="delay"
dict["verschweissen"]="weld"
dict["versorgen"]="care"
dict["versprechen"]="promise"
dict["verteilen"]="distribute"
dict["vertrauen"]="trust"
dict["verursachen"]="provoke"
dict["verweisen"]="refer"
dict["verwenden"]="use"
dict["verzichten"]="deny"
dict["vorbeikommen"]="pass"
dict["vorkommen"]="occur"
dict["vorschlagen"]="suggest"
dict["vorziehen"]="choose"
dict["wachsen"]="grow"
dict["wecken"]="wake"
dict["wegwerfen"]="throw away"
dict["weitergeben"]="pass"
dict["wenden"]="turn"
dict["werfen"]="throw"
dict["widmen"]="dedicate"
dict["wirken"]="act"
dict["wurzen"]="spice"
dict["ziehen"]="pull"
dict["zogern"]="hesitate"
dict["zubereiten"]="prepair"
dict["zugeben"]="admit"
dict["zuordnen"]="arrange"
dict["zurechtlegen"]="arrange"
dict["zusagen"]="accept"
dict["zusammenlegen"]="fold"
dict["zusammenpassen"]="match"
dict["zusehen"]="observe"
dict["zuruckkehren"]="return"
dict["zwingen"]="force"



function quiz() {
    while true; do
        key=$(shuf -n 1 -e "${!dict[@]}")  # Pick a random word
        clear
	read -p "What is '$key'? " answer

        if [[ "$answer" == "exit" ]]; then
            echo -e "\nGame Over 🎉"
            echo "Correct answers: $correct"
            echo "Wrong answers: $wrong"
            sleep 3
	    clear
	    break
        elif [[ "$answer" == "${dict[$key]}" ]]; then
            echo -e "\n✅ Correct!\n"
            ((correct++))
	    sleep 1
        else
            echo -e "\n❌ Wrong! The answer is: ${dict[$key]}\n"
            ((wrong++))
	    sleep 2
        fi
    done
}

quiz
